# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/MusifyApp

# Cloudinary Configuration
cloudinary.cloud-name=dc7kbbhsr
cloudinary.api-key=771748567529162
cloudinary.api-secret=Gtvk6gXE-JgntyIXpMPDvQLiSaU

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB